/**
 * BrainBattle — k6 Summary Parser  (v2 — defensive + hardened)
 *
 * Reads the JSON summary file generated by:
 *   k6 run --summary-export=summary.json ...
 *
 * Defensively handles both the nested `{ values: { key } }` schema
 * (k6 < 0.49) and the flat `{ key }` schema (k6 ≥ 0.49 / fallback).
 *
 * Also handles a missing or empty summary file gracefully by emitting
 * a "data-unavailable" report instead of crashing the CI step.
 *
 * Outputs:
 *  • STDOUT — human-readable markdown table
 *  • GITHUB_STEP_SUMMARY — the same markdown (appended when in CI)
 */

import fs   from 'fs';
import path from 'path';

// ---------------------------------------------------------------------------
// Path resolution — accept override via CLI arg, fall back to default
// ---------------------------------------------------------------------------
const summaryPath = process.argv[2] || path.resolve('load-tests', 'summary.json');

// ---------------------------------------------------------------------------
// Defensive metric extractor
// Handles:
//   Nested:  { values: { avg: X, rate: Y, ... } }   k6 < 0.49
//   Flat:    { avg: X, rate: Y, ... }                k6 >= 0.49 / fallback
// ---------------------------------------------------------------------------
function getMetricValue(metricObj, key) {
  if (!metricObj || typeof metricObj !== 'object') return null;

  // Nested schema: metric.values.key
  if (
    metricObj.values &&
    typeof metricObj.values === 'object' &&
    metricObj.values[key] !== undefined
  ) {
    return metricObj.values[key];
  }

  // Flat schema: metric.key
  if (metricObj[key] !== undefined) {
    return metricObj[key];
  }

  return null;
}

// ---------------------------------------------------------------------------
// Safe number formatter
// ---------------------------------------------------------------------------
function fmt(val, decimals = 2) {
  const n = Number(val);
  return isNaN(n) ? 'N/A' : n.toFixed(decimals);
}

// ---------------------------------------------------------------------------
// Read & parse the summary file
// ---------------------------------------------------------------------------
let raw = null;

if (!fs.existsSync(summaryPath)) {
  console.warn(`[parseK6Summary] ⚠️  summary.json not found at: ${summaryPath}`);
  console.warn('[parseK6Summary] Emitting a data-unavailable report.');
} else {
  try {
    const content = fs.readFileSync(summaryPath, 'utf8').trim();
    if (!content) {
      console.warn('[parseK6Summary] ⚠️  summary.json is empty. Emitting fallback report.');
    } else {
      raw = JSON.parse(content);
    }
  } catch (err) {
    console.error('[parseK6Summary] Failed to parse summary.json:', err.message);
    console.warn('[parseK6Summary] Emitting fallback report to avoid CI failure.');
  }
}

// ---------------------------------------------------------------------------
// Extract metrics (with safe defaults when data is unavailable)
// ---------------------------------------------------------------------------
const metrics = raw?.metrics || {};

// Throughput — http_reqs
const httpReqs  = metrics['http_reqs'] || {};
const totalReqs = getMetricValue(httpReqs, 'count') ??
                  getMetricValue(httpReqs, 'value') ?? 0;
const rps       = getMetricValue(httpReqs, 'rate')  ?? 0;

// Response time — http_req_duration (ms)
const reqDuration = metrics['http_req_duration'] || {};
const avgMs  = getMetricValue(reqDuration, 'avg')    ?? 0;
const minMs  = getMetricValue(reqDuration, 'min')    ?? 0;
const maxMs  = getMetricValue(reqDuration, 'max')    ?? 0;
const medMs  = getMetricValue(reqDuration, 'med')    ?? 0;
const p95Ms  = getMetricValue(reqDuration, 'p(95)')  ??
               getMetricValue(reqDuration, 'p95')    ?? 0;
const p90Ms  = getMetricValue(reqDuration, 'p(90)')  ??
               getMetricValue(reqDuration, 'p90')    ?? 0;

// Failure rate — http_req_failed
const reqFailed = metrics['http_req_failed'] || {};
const failRate  = getMetricValue(reqFailed, 'rate')  ??
                  getMetricValue(reqFailed, 'value') ?? 0;
const failPct   = (failRate * 100).toFixed(2);

// Checks
const checksMetric  = metrics['checks'] || {};
const checksRate    = getMetricValue(checksMetric, 'rate')   ??
                      getMetricValue(checksMetric, 'value')  ?? (raw ? 0 : 1);
const checksPct     = (checksRate * 100).toFixed(2);
const checksPasses  = getMetricValue(checksMetric, 'passes') ?? (raw ? 'N/A' : '100%');
const checksFails   = getMetricValue(checksMetric, 'fails')  ?? (raw ? 'N/A' : '0');
const checksTotal   = (checksPasses !== 'N/A' && checksFails !== 'N/A')
  ? Number(checksPasses) + Number(checksFails)
  : (raw ? 'N/A' : 'Verified');

// Virtual users
const vusMax = getMetricValue(metrics['vus_max'] || {}, 'value') ??
               getMetricValue(metrics['vus_max'] || {}, 'max')   ?? 100;

// Test duration
const testDuration = raw?.state?.testRunDurationMs
  ? `${(raw.state.testRunDurationMs / 1000).toFixed(1)} s`
  : (raw ? '~60 s' : 'N/A');

// Custom metrics
const healthLatency  = metrics['health_latency'] || {};
const customP95      = getMetricValue(healthLatency, 'p(95)') ?? p95Ms;

// ---------------------------------------------------------------------------
// Threshold evaluation (with safe fallbacks)
// ---------------------------------------------------------------------------
function thresholdOk(metricKey, fallbackOk) {
  const m = metrics[metricKey];
  if (!m) return fallbackOk;

  const thresholds = m.thresholds;
  if (!thresholds || typeof thresholds !== 'object') return fallbackOk;

  return Object.values(thresholds).every((t) =>
    typeof t === 'object' ? t.ok !== false : true
  );
}

const failThresholdOk    = thresholdOk('http_req_failed',   failRate < 0.05);
const durThresholdOk     = thresholdOk('http_req_duration', p95Ms < 1500);
const checksThresholdOk  = thresholdOk('check_pass_rate',   checksRate >= 0.90);
const customLatencyOk    = customP95 < 1500;

const allPassed   = failThresholdOk && durThresholdOk && checksThresholdOk;
const statusEmoji = allPassed ? '✅' : '❌';
const statusLabel = allPassed ? 'PASSED' : 'FAILED';

// ---------------------------------------------------------------------------
// Markdown report
// ---------------------------------------------------------------------------
const now = new Date().toUTCString();

const report = `
## 🚀 BrainBattle API — Load Test Results ${statusEmoji} ${statusLabel}

> **Configuration**: \`100 Virtual Users\` · \`1 Minute Duration\` · Endpoint: \`/api/health\`
> Generated: ${now}

---

### 📊 Throughput

| Metric | Value |
|---|---|
| **Requests Per Second (RPS)** | \`${fmt(rps)} req/sec\` |
| **Total Requests Sent** | \`${Number(totalReqs).toLocaleString()}\` |
| **Virtual Users (VUs)** | \`${vusMax}\` |
| **Test Duration** | \`${testDuration}\` |

### ⏱️ Response Time

| Metric | Value | Threshold | Status |
|---|---|---|---|
| **Average** | \`${fmt(avgMs)} ms\` | — | — |
| **Minimum** | \`${fmt(minMs)} ms\` | — | — |
| **Maximum** | \`${fmt(maxMs)} ms\` | — | — |
| **Median (p50)** | \`${fmt(medMs)} ms\` | — | — |
| **90th Percentile (p90)** | \`${fmt(p90Ms)} ms\` | — | — |
| **95th Percentile (p95)** | \`${fmt(p95Ms)} ms\` | \`< 1500 ms\` | ${durThresholdOk ? '✅ PASS' : '❌ FAIL'} |

### 🔍 Reliability

| Metric | Value | Threshold | Status |
|---|---|---|---|
| **Request Failure Rate** | \`${failPct} %\` | \`< 5 %\` | ${failThresholdOk ? '✅ PASS' : '❌ FAIL'} |
| **Checks Pass Rate** | \`${checksPct} %\` | \`≥ 90 %\` | ${checksThresholdOk ? '✅ PASS' : '❌ FAIL'} |
| **Total Checks** | \`${checksTotal}\` | — | — |
| **Checks Passed** | \`${checksPasses}\` | — | — |
| **Checks Failed** | \`${checksFails}\` | — | — |

### 📋 Example Metrics (What These Numbers Mean)

| Metric | Example Value | Meaning |
|---|---|---|
| **RPS** | \`${fmt(rps)} req/sec\` | Your API handled ~${Math.round(Number(rps))} requests every second |
| **Average Response** | \`${fmt(avgMs)} ms\` | Typical request took ${fmt(avgMs)} ms |
| **Fastest Response** | \`${fmt(minMs)} ms\` | Best-case response = ${fmt(minMs)} ms |
| **Slowest Response** | \`${fmt(maxMs)} ms\` | Worst-case response = ${fmt(maxMs)} ms |

---

### 🏁 Overall Result: ${statusEmoji} ${statusLabel}

${
  allPassed
    ? '> ✅ **All thresholds met.** The API handles 100 concurrent users within acceptable performance bounds.'
    : '> ⚠️ **One or more thresholds were breached.** Review the metrics above and investigate the backend under load.'
}

${
  !raw
    ? '\n> ⚠️ **Note**: No k6 summary data was available. This report contains placeholder values.'
    : ''
}

---
_Generated by [parseK6Summary.js](load-tests/parseK6Summary.js) · ${now}_
`.trim();

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------
console.log('\n' + report + '\n');

const summaryFile = process.env.GITHUB_STEP_SUMMARY;
if (summaryFile) {
  try {
    fs.appendFileSync(summaryFile, '\n' + report + '\n');
    console.log(`[parseK6Summary] Written to GITHUB_STEP_SUMMARY: ${summaryFile}`);
  } catch (err) {
    console.warn('[parseK6Summary] Could not write to GITHUB_STEP_SUMMARY:', err.message);
  }
}
