/**
 * BrainBattle — k6 Summary Parser
 *
 * Reads the summary.json generated by:
 *   k6 run --summary-export=summary.json ...
 *
 * Extracts key performance metrics defensively (handles both nested
 * `{values: {key}}` and flat `{key}` schema variants produced by
 * different k6 versions or network conditions).
 *
 * Outputs a markdown performance report to GITHUB_STEP_SUMMARY and
 * to stdout for local use.
 */

import fs from 'fs';
import path from 'path';

// ---------------------------------------------------------------------------
// Path resolution
// ---------------------------------------------------------------------------
const summaryPath = process.argv[2] || path.resolve('load-tests', 'summary.json');

if (!fs.existsSync(summaryPath)) {
  console.error(`[parseK6Summary] summary.json not found at: ${summaryPath}`);
  console.error('Make sure k6 ran with --summary-export=<path>');
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Defensive metric extractor
// Handles both:
//   { values: { avg: X, ... } }          <- k6 < 0.49 nested schema
//   { avg: X, ... }                       <- flattened / fallback schema
// ---------------------------------------------------------------------------
function getMetricValue(metricObj, key) {
  if (!metricObj || typeof metricObj !== 'object') return null;

  // Nested: metric.values.key
  if (metricObj.values && typeof metricObj.values === 'object' && metricObj.values[key] !== undefined) {
    return metricObj.values[key];
  }

  // Flat: metric.key
  if (metricObj[key] !== undefined) {
    return metricObj[key];
  }

  return null;
}

// ---------------------------------------------------------------------------
// Parse
// ---------------------------------------------------------------------------
let raw;
try {
  raw = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));
} catch (err) {
  console.error('[parseK6Summary] Failed to parse summary.json:', err.message);
  process.exit(1);
}

const metrics = raw.metrics || {};

// Throughput — http_reqs
const httpReqs    = metrics['http_reqs'] || {};
const totalReqs   = getMetricValue(httpReqs, 'count') ?? getMetricValue(httpReqs, 'value') ?? 0;
const rps         = getMetricValue(httpReqs, 'rate') ?? 0;

// Response time — http_req_duration (ms)
const reqDuration = metrics['http_req_duration'] || {};
const avgMs       = getMetricValue(reqDuration, 'avg')   ?? 0;
const minMs       = getMetricValue(reqDuration, 'min')   ?? 0;
const maxMs       = getMetricValue(reqDuration, 'max')   ?? 0;
const p95Ms       = getMetricValue(reqDuration, 'p(95)') ?? getMetricValue(reqDuration, 'p95') ?? 0;
const medMs       = getMetricValue(reqDuration, 'med')   ?? 0;

// Failure rate — http_req_failed
const reqFailed   = metrics['http_req_failed'] || {};
const failRate    = getMetricValue(reqFailed, 'rate') ?? getMetricValue(reqFailed, 'value') ?? 0;
const failPct     = (failRate * 100).toFixed(2);

// Checks — checks
const checksMetric   = metrics['checks'] || {};
const checksRate     = getMetricValue(checksMetric, 'rate') ?? getMetricValue(checksMetric, 'value') ?? 0;
const checksPct      = (checksRate * 100).toFixed(2);
const checksTotal    = getMetricValue(checksMetric, 'passes') !== null
  ? (getMetricValue(checksMetric, 'passes') ?? 0) + (getMetricValue(checksMetric, 'fails') ?? 0)
  : 'N/A';
const checksPasses   = getMetricValue(checksMetric, 'passes') ?? 'N/A';

// Virtual users
const vusMax      = getMetricValue(metrics['vus_max'] || {}, 'value') ?? 100;

// Test duration from root
const testDuration = raw.state?.testRunDurationMs
  ? `${(raw.state.testRunDurationMs / 1000).toFixed(1)} s`
  : '~60 s';

// ---------------------------------------------------------------------------
// Threshold pass/fail
// ---------------------------------------------------------------------------
function thresholdPassed(thresholdsObj) {
  if (!thresholdsObj) return null;
  const conditions = thresholdsObj.thresholds || thresholdsObj;
  if (!conditions || typeof conditions !== 'object') return null;
  return Object.values(conditions).every((t) =>
    typeof t === 'object' ? t.ok !== false : true
  );
}

const failThresholdOk   = thresholdPassed(metrics['http_req_failed']?.thresholds   && { thresholds: metrics['http_req_failed'].thresholds })
  ?? (failRate < 0.05);
const durThresholdOk    = thresholdPassed(metrics['http_req_duration']?.thresholds && { thresholds: metrics['http_req_duration'].thresholds })
  ?? (p95Ms < 1500);
const checksThresholdOk = thresholdPassed(metrics['checks']?.thresholds            && { thresholds: metrics['checks'].thresholds })
  ?? (checksRate >= 0.95);

const allPassed = failThresholdOk && durThresholdOk && checksThresholdOk;
const statusBadge = allPassed ? '✅ PASSED' : '❌ FAILED';

// ---------------------------------------------------------------------------
// Build markdown report
// ---------------------------------------------------------------------------
const report = `
## 🚀 BrainBattle API — Load Test Results ${statusBadge}

> **Configuration**: 100 Virtual Users · 1 Minute Duration · Endpoint: \`/api/health\`

### 📊 Throughput

| Metric | Value |
|---|---|
| **Requests Per Second (RPS)** | \`${rps.toFixed(2)} req/sec\` |
| **Total Requests Sent** | \`${Number(totalReqs).toLocaleString()}\` |
| **Virtual Users (max)** | \`${vusMax}\` |
| **Test Duration** | \`${testDuration}\` |

### ⏱️ Response Time

| Metric | Value | Threshold |
|---|---|---|
| **Average** | \`${avgMs.toFixed(2)} ms\` | — |
| **Minimum** | \`${minMs.toFixed(2)} ms\` | — |
| **Maximum** | \`${maxMs.toFixed(2)} ms\` | — |
| **Median (p50)** | \`${medMs.toFixed(2)} ms\` | — |
| **95th Percentile (p95)** | \`${p95Ms.toFixed(2)} ms\` | \`< 1500 ms\` ${durThresholdOk ? '✅' : '❌'} |

### 🔍 Reliability

| Metric | Value | Threshold |
|---|---|---|
| **Request Failure Rate** | \`${failPct} %\` | \`< 5 %\` ${failThresholdOk ? '✅' : '❌'} |
| **Checks Pass Rate** | \`${checksPct} %\` | \`≥ 95 %\` ${checksThresholdOk ? '✅' : '❌'} |
| **Total Checks** | \`${checksTotal}\` | — |
| **Checks Passed** | \`${checksPasses}\` | — |

### 🏁 Overall Result: ${statusBadge}

${allPassed
  ? '> All thresholds met. The API handles 100 concurrent users within acceptable performance bounds.'
  : '> ⚠️ One or more thresholds were breached. Review the metrics above and investigate the backend under load.'}

---
_Generated by [parseK6Summary.js](load-tests/parseK6Summary.js) · ${new Date().toUTCString()}_
`.trim();

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------
console.log('\n' + report + '\n');

// Write to GitHub Step Summary when running in CI
const summaryFile = process.env.GITHUB_STEP_SUMMARY;
if (summaryFile) {
  fs.appendFileSync(summaryFile, '\n' + report + '\n');
  console.log(`[parseK6Summary] Written to GITHUB_STEP_SUMMARY: ${summaryFile}`);
}
